### ISSUE TITLE
Compatibility mashup 0.9.21-nightly

### ISSUE THREAD

**Issue by Massimo-B** [ds10git/fidorcsv#1]
Hi, currently I get a failure message, that fidorcsv is not compatible to mashup 0.9.21-nightly.

**Comment by ds10git** [comment]
The plugins fidorcsv and mashup have nothing to do with each other. The mashup plugin is not needed for fidorcsv to function properly. But mashup also includes the integration of Fidor so maybe it was changed so that it want's you to remove fidorcsv because fidorcsv tries to set itself as the plugin used for Fidor bank accounts. So you either could use mashup or fidorcsv to synchronize with Fidor.

**Comment by Massimo-B** [comment]
Ok, maybe I missed something in the past. So far I always downloaded the file manually and imported manually from local directory. Now after removing the fidorcsv plugin and thus using the mashup integration, it's just working online by asking password and TAN, did create the export file manually, downloaded and imported. Thank you very much.
